apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-backend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nova-backend
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: nova-backend
    spec:
      serviceAccountName: nova-backend-sa
      containers:
        - name: nova
          image: nova-backend-image:template
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: 3000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /api
              port: 3000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          resources:
            limits:
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
      restartPolicy: Always
