# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

resources:
  - vault/vaultAuth.yaml
  - vault/vaultStaticSecret.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - istio/allow-ingress-authorization-policy.yaml

labels:
  - pairs:
      app: nova-backend
      env: ENV_PLACEHOLDER
      app.kubernetes.io/name: nova-backend
