resources:
  - ../../base

namespace: nova

configMapGenerator:
  - name: nova-backend-configs
    envs:
      - params.env

patches:
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount
      name: nova-backend-sa
  - path: patches/allow-ingress.yaml
    target:
      kind: AuthorizationPolicy

labels:
  - pairs:
      env: dev

images:
  - name: nova-backend-image:template
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/nova/api
    newTag: "1739959086"
