# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

# FROM nginxinc/nginx-unprivileged:1.29.5-alpine3.23
FROM nginxinc/nginx-unprivileged:1.31.3-alpine3.24

# Patch OS-level packages to pick up latest security fixes (Trivy)
USER root
RUN apk update && apk upgrade --no-cache
USER 101

COPY frontend/dist /usr/share/nginx/html
