FROM node:23-alpine

# Set working directory
WORKDIR /home/node/app

# Install dependencies
COPY ./api/package*.json ./
RUN npm ci

# Copy the full source code
COPY ./api ./

# Build the TypeScript code
RUN npm run build

# Use non-root user
USER node

# Expose the API port
EXPOSE 3000
ENV HOST=0.0.0.0

# Run the compiled app
CMD ["node", "dist/server.js"]
