# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    io.kompose.service: nova-frontend
  name: nova-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nova-frontend
  template:
    metadata:
      annotations: {}
      labels:
        io.kompose.service: nova-frontend
    spec:
      serviceAccountName: nova-frontend-sa
      containers:
        - image: nova-frontend-image:template
          env:
            - name: IMAGE_DIGEST
              value: "none"
          name: frontend
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
              ephemeral-storage: "2Gi"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
