apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    io.kompose.service: nova-frontend
  name: nova-frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  type: NodePort
  selector:
    io.kompose.service: nova-frontend
