apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-backend-env
spec:
  template:
    spec:
      containers:
        - name: backend-env
          env:
            - name: NODE_ENV
              value: "production"
            - name: IDENTITY_API_URL
              value: "http://landing-page-api.landing-page.svc.cluster.local"
            - name: LANDING_PAGE_URL
              value: "https://landing.dev.ndtp.co.uk"
