# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

- op: replace
  path: "/metadata/annotations/eks.amazonaws.com~1role-arn"
  value: arn:aws:iam::503561419905:role/nova-frontend-access-role
